import { Course, StatePath } from '../types';

/**
 * Teacher assignment links.
 *
 * A teacher picks a question and shares a URL; a student opening it lands
 * directly on that question. The link encodes the full syllabus path
 * (course → topic → sub-topic → dot point → question) as five comma-joined,
 * URI-encoded ids in an `assign` query parameter.
 *
 * The ids must exist in the OPENING user's course library — true whenever
 * both sides use the shared/remote curriculum, or the teacher exported the
 * course to the class. `resolveAssignmentPath` validates every level and
 * returns null (rather than a broken half-selection) when anything is missing.
 *
 * Ids are generated by generateId() — `<prefix>-<uuid>` — so they only ever
 * contain URL-safe characters (letters, digits, hyphens) and never the comma
 * separator. That keeps the wire format a plain comma-joined string with no
 * per-part encoding to get tangled up with URLSearchParams' own decoding.
 */

const PARAM_SEPARATOR = ',';

export const ASSIGNMENT_PARAM = 'assign';

/** Builds the shareable URL, or null while any level is still unselected. */
export const buildAssignmentLink = (
  path: StatePath,
  baseUrl: string = typeof window !== 'undefined'
    ? `${window.location.origin}${import.meta.env.BASE_URL}`
    : ''
): string | null => {
  const { courseId, topicId, subTopicId, dotPointId, promptId } = path;
  if (!courseId || !topicId || !subTopicId || !dotPointId || !promptId) return null;
  const joined = [courseId, topicId, subTopicId, dotPointId, promptId].join(PARAM_SEPARATOR);
  const base = baseUrl.endsWith('/') ? baseUrl : `${baseUrl}/`;
  return `${base}?${ASSIGNMENT_PARAM}=${joined}`;
};

/**
 * Parses the `assign` parameter back into a candidate path. Pass the value
 * already read from URLSearchParams.get() (which has done any URL-decoding).
 */
export const parseAssignmentParam = (raw: string | null): StatePath | null => {
  if (!raw) return null;
  const parts = raw.split(PARAM_SEPARATOR);
  if (parts.length !== 5 || parts.some((p) => !p)) return null;
  const [courseId, topicId, subTopicId, dotPointId, promptId] = parts;
  return { courseId, topicId, subTopicId, dotPointId, promptId };
};

/**
 * Validates a candidate assignment path against the user's course library.
 * Returns the confirmed path plus the question text (for the confirmation
 * toast), or null when any level of the hierarchy is missing.
 */
export const resolveAssignmentPath = (
  courses: Course[],
  candidate: StatePath | null
): { path: StatePath; question: string } | null => {
  if (!candidate) return null;
  const course = courses.find((c) => c.id === candidate.courseId);
  const topic = course?.topics.find((t) => t.id === candidate.topicId);
  const subTopic = topic?.subTopics.find((st) => st.id === candidate.subTopicId);
  const dotPoint = subTopic?.dotPoints.find((dp) => dp.id === candidate.dotPointId);
  const prompt = dotPoint?.prompts.find((p) => p.id === candidate.promptId);
  if (!prompt) return null;
  return {
    path: {
      courseId: candidate.courseId,
      topicId: candidate.topicId,
      subTopicId: candidate.subTopicId,
      dotPointId: candidate.dotPointId,
      promptId: candidate.promptId,
    },
    question: prompt.question,
  };
};
